version: '3'

services:
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./docker/init/db:/docker-entrypoint-initdb.d
    ports:
      - '5432'
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - '3000:3000'
    volumes:
      - .:/myapp
      - /myapp/log
      - /myapp/.git
      - bigquery-bundle:/usr/local/bundle
    depends_on:
      - postgres
    tty: true
    stdin_open: true
volumes:
  postgresql-data:
    driver: local
  bigquery-bundle:
    driver: local
